# ============================================
# ToolsPlugin Configuration
# Wersja: 1.0.1
# ============================================

database:
  type: "mysql"     # albo "sqlite"
  host: "localhost" # ignorowane przy sqlite
  port: 3306        # ignorowane przy sqlite
  database: "toolsplugin"
  username: "root"  # ignorowane przy sqlite
  password: ""      # ignorowane przy sqlite

settings:
  prefix-enabled: true
  prefix: "&8[&6ToolsPlugin&8] &r"

permissions:
  bypass-cooldowns: "tfbhc.bypass.cooldown"

chat:
  default-format: "%prefix%%player_name%%suffix%&f: &7%message%"
  format: "&f[%prefix%%player_name%%suffix%&f]: &7%message%"
  custom-formats:
    admin:
      permission: "tfbhc.chat.format.admin"
      format: "&c[ADMIN] %player_name% &7>> &f%message%"
    vip:
      permission: "tfbhc.chat.format.vip"
      format: "&6[VIP] %player_name% &7>> &f%message%"

teleport:
  safe-teleport: true
  delay: 3
  cancel-on-move: true
  cancel-on-damage: true

spawn:
  world: ""      # Ustaw poprzez /setspawn
  x: 0.0
  y: 64.0
  z: 0.0
  yaw: 0.0
  pitch: 0.0